# Generated by Django 5.1.6 on 2025-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='utmBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicKye', models.CharField(max_length=100)),
                ('utms', models.CharField(blank=True, max_length=500, null=True)),
                ('linkbase', models.ManyToManyField(related_name='links', to='redirector.linkbase')),
            ],
        ),
    ]
